site_name: "truzt"
site_url: "https://yutaka-shoji.truzt.github.io/"

theme:
  name: "material"
  features:
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

repo_name: yutaka-shoji/truzt
repo_url: https://github.com/yutaka-shoji/truzt
copyright: Copyright &copy; 2024 Shoji, Yutaka

nav:
  - Home:
      - Overview: index.md
      - License: license.md
  - Reference: reference/

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            members_order: alphabetical

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
