# generated by datamodel-codegen:
#   filename:  webproJsonSchema.json
#   timestamp: 2024-08-07T13:41:06+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union, Literal

from pydantic import BaseModel, Field


class BuildingAddress(BaseModel):
    class Config:
        extra = ("forbid",)

    Prefecture: Optional[str] = Field(..., description="BL-2:都道府県")
    City: Optional[str] = Field(..., description="BL-3:市区町村")
    Address: Optional[str] = Field(..., description="BL-4:丁目、番地等")


class CoefficientDHC(BaseModel):
    class Config:
        extra = ("forbid",)

    Cooling: Optional[float] = Field(..., description="BL-8:冷熱")
    Heating: Optional[float] = Field(..., description="BL-9:温熱")


class Zone(BaseModel):
    zoneArea: Optional[float] = Field(None, ge=0, description="RM-9:ゾーン面積")


class Rooms(BaseModel):
    buildingType: Optional[
        Literal[
            "事務所等",
            "ホテル等",
            "病院等",
            "物販店舗等",
            "学校等",
            "飲食店等",
            "集会所等",
            "工場等",
            "共同住宅",
        ]
    ] = Field(None, description="RM-3:建物用途")
    roomType: Optional[str] = Field(None, description="RM-4:室用途")
    floorHeight: Optional[float] = Field(None, ge=0, description="RM-5:階高")
    ceilingHeight: Optional[float] = Field(None, ge=0, description="RM-6:天井高")
    roomArea: Optional[float] = Field(None, ge=0, description="RM-7:床面積")
    zone: Optional[Dict[str, Zone]] = None
    modelBuildingType: Optional[str] = Field(None, description="RM-10:モデル建物")
    buildingGroup: Optional[str] = Field(None, description="RM-11:建物群名称")


class WindowListItem(BaseModel):
    WindowID: Optional[str] = Field(None, description="BE1-11:開口部仕様名称")
    WindowNumber: Optional[int] = Field(None, ge=0, description="BE1-12:建具等個数")
    isBlind: Optional[Literal["有", "無"]] = Field(
        None,
        description="BE1-13:ブラインドの有無",
    )
    EavesID: Optional[str] = Field(None, description="BE1-14:日除けの名称")
    Info: Optional[str] = Field(None, description="BE1-15:備考")


class WallListItem(BaseModel):
    Direction: Optional[
        Literal[
            "北",
            "北東",
            "東",
            "南東",
            "南",
            "南西",
            "西",
            "北西",
            "水平（上）",
            "水平（下）",
        ]
    ] = Field(None, description="BE1-5:方位")
    EnvelopeArea: Optional[float] = Field(None, ge=0, description="BE1-6:外皮面積")
    EnvelopeWidth: Optional[float] = Field(None, ge=0, description="BE1-7:外皮の幅")
    EnvelopeHeight: Optional[float] = Field(None, ge=0, description="BE1-8:外皮の高さ")
    WallSpec: Optional[str] = Field(None, description="BE1-9:断熱仕様名称")
    WallType: Optional[
        Literal["日の当たる外壁", "日の当たらない外壁", "地盤に接する外壁", "内壁"]
    ] = Field(None, description="BE1-10:外壁の種類")
    WindowList: Optional[List[WindowListItem]] = None


class EnvelopeSet(BaseModel):
    isAirconditioned: Optional[Literal["有", "無"]] = Field(
        None,
        description="BE1-4:空調の有無",
    )
    WallList: Optional[List[WallListItem]] = None


class Layer(BaseModel):
    materialID: Optional[str] = Field(None, description="BE2-7:断熱材の種類")
    conductivity: Optional[float] = Field(None, ge=0.0, description="BE2-8:熱伝導率")
    thickness: Optional[float] = Field(None, ge=0, description="BE2-9:厚み")
    Info: Optional[str] = Field(None, description="BE2-11:備考")


class WallConfigure(BaseModel):
    structureType: Optional[
        Literal["木造", "鉄筋コンクリート造等", "鉄骨造", "その他"]
    ] = Field(None, description="BE2-2:構造種別")
    solarAbsorptionRatio: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description="BE2-3:日射吸収率",
    )
    inputMethod: Optional[
        Literal["熱貫流率を入力", "建材構成を入力", "断熱材種類を入力"]
    ] = Field(None, description="断熱性能の入力方法")
    materialID: Optional[str] = Field(None, description="BE2-4:断熱材の種類")
    conductivity: Optional[float] = Field(None, ge=0.0, description="BE2-5:熱伝導率")
    thickness: Optional[float] = Field(None, ge=0, description="BE2-6:厚み")
    Uvalue: Optional[float] = Field(None, ge=0.0, description="BE2-10:熱貫流率")
    Info: Optional[str] = Field(None, description="BE2-11:備考")
    layers: Optional[List[Layer]] = None


class WindowConfigure(BaseModel):
    windowArea: Optional[float] = Field(None, ge=0.0, description="BE3-2:窓面積")
    windowWidth: Optional[float] = Field(None, ge=0.0, description="BE3-3:窓の幅")
    windowHeight: Optional[float] = Field(None, ge=0.0, description="BE3-4:窓の高さ")
    inputMethod: Optional[
        Literal["性能値を入力", "ガラスの性能を入力", "ガラスの種類を入力"]
    ] = Field(None, description="窓性能の入力方法")
    frameType: Optional[
        Literal["樹脂製", "木製", "金属樹脂複合製", "金属木複合製", "金属製"]
    ] = Field(None, description="BE3-5:建具の種類")
    glassID: Optional[str] = Field(None, description="BE3-6:ガラス建築確認記号")
    layerType: Optional[Literal["複層", "単層"]] = Field(
        None,
        description="BE3-7:ガラスの層数",
    )
    glassUvalue: Optional[float] = Field(
        None,
        ge=0.0,
        description="BE3-8:ガラスの熱貫流率",
    )
    glassIvalue: Optional[float] = Field(
        None,
        ge=0.0,
        description="BE3-9:ガラスの日射熱取得率",
    )
    windowUvalue: Optional[float] = Field(
        None,
        ge=0.0,
        description="BE3-10:窓の熱貫流率",
    )
    windowIvalue: Optional[float] = Field(
        None,
        ge=0.0,
        description="BE3-11:窓の日射熱取得率",
    )
    Info: Optional[str] = Field(None, description="BE3-12:備考")


class ShadingLength(BaseModel):
    __root__: Optional[float] = Field(..., ge=0.0, description="BE4-4〜13:日除けの形状")


class AirConditioningZone(BaseModel):
    isNatualVentilation: Optional[Literal["無", "有"]] = Field(
        None,
        description="AC1-4:自然換気の有無",
    )
    isSimultaneousSupply: Optional[
        Literal["無", "有", "有（室負荷）", "有（外気負荷）"]
    ] = Field(
        None,
        description="AC1-5:冷暖同時供給の有無",
    )
    AHU_cooling_insideLoad: Optional[str] = Field(
        None,
        description="AC1-6:空調機群名称 冷房 室負荷処理",
    )
    AHU_cooling_outdoorLoad: Optional[str] = Field(
        None,
        description="AC1-7:空調機群名称 冷房 外気負荷処理",
    )
    AHU_heating_insideLoad: Optional[str] = Field(
        None,
        description="AC1-8:空調機群名称 暖房 室負荷処理",
    )
    AHU_heeating_outdoorLoad: Optional[str] = Field(
        None,
        description="AC1-9:空調機群名称 暖房 外気負荷処理",
    )
    Info: Optional[str] = Field(None, description="AC1-10:備考")


class HeatsourceItem(BaseModel):
    HeatsourceType: Optional[str] = Field(None, description="AC2-6:熱源機種")
    Number: Optional[int] = Field(None, ge=0, description="AC2-7:台数")
    SupplyWaterTempSummer: Optional[float] = Field(
        None,
        description="AC2-8:送水温度 夏期",
    )
    SupplyWaterTempMiddle: Optional[float] = Field(
        None,
        description="AC2-9:送水温度 中間期",
    )
    SupplyWaterTempWinter: Optional[float] = Field(
        None,
        description="AC2-10:送水温度 冬期",
    )
    HeatsourceRatedCapacity: Optional[float] = Field(
        None,
        ge=0.0,
        description="AC2-11:熱源本体 定格能力",
    )
    HeatsourceRatedPowerConsumption: Optional[float] = Field(
        None,
        ge=0.0,
        description="AC2-12:熱源主機 定格消費電力",
    )
    HeatsourceRatedFuelConsumption: Optional[float] = Field(
        None,
        ge=0.0,
        description="AC2-13:熱源主機 定格燃料消費量",
    )
    Heatsource_sub_RatedPowerConsumption: Optional[float] = Field(
        None,
        ge=0.0,
        description="AC2-14:熱源補機 定格消費電力",
    )
    PrimaryPumpPowerConsumption: Optional[float] = Field(
        None,
        ge=0.0,
        description="AC2-15:一次ポンプ 定格消費電力",
    )
    PrimaryPumpContolType: Optional[Literal["有", "無"]] = Field(
        None,
        description="AC2-16:一次ポンプ 制御方式",
    )
    CoolingTowerCapacity: Optional[float] = Field(
        None,
        ge=0.0,
        description="AC2-17:冷却塔 定格能力",
    )
    CoolingTowerFanPowerConsumption: Optional[float] = Field(
        None,
        ge=0.0,
        description="AC2-18:冷却塔 ファン消費電力",
    )
    CoolingTowerPumpPowerConsumption: Optional[float] = Field(
        None,
        ge=0.0,
        description="AC2-19:冷却塔 ポンプ消費電力",
    )
    CoolingTowerContolType: Optional[Literal["有", "無"]] = Field(
        None,
        description="AC2-20:冷却塔 制御方式",
    )
    Info: Optional[str] = Field(None, description="AC2-21:備考")


class Heatsource(BaseModel):
    StorageType: Optional[Literal["水蓄熱(混合型)", "水蓄熱(成層型)", "氷蓄熱"]] = (
        Field(None, description="AC2-3:蓄熱の種類")
    )
    StorageSize: Optional[float] = Field(
        None,
        ge=0.0,
        description="AC2-4:蓄熱容量",
    )
    isStagingControl: Optional[Literal["有", "無"]] = Field(
        None,
        description="AC2-5:台数制御",
    )
    Heatsource: Optional[List[HeatsourceItem]] = None


class SecondaryPumpItem(BaseModel):
    Number: Optional[int] = Field(
        None,
        ge=0,
        description="AC3-5:台数",
    )
    RatedWaterFlowRate: Optional[float] = Field(
        None,
        ge=0.0,
        description="AC3-6:定格流量",
    )
    RatedPowerConsumption: Optional[float] = Field(
        None,
        ge=0.0,
        description="AC3-7:定格消費電力",
    )
    ContolType: Optional[Literal["無", "定流量制御", "回転数制御"]] = Field(
        None, description="AC3-8:制御方式"
    )
    MinOpeningRate: Optional[float] = Field(
        None,
        ge=0.0,
        le=100.0,
        description="AC3-9:最小流量比",
    )
    Info: Optional[str] = Field(None, description="AC3-10:備考")


class SecondaryPump(BaseModel):
    TempelatureDifference: Optional[float] = Field(
        None,
        ge=0.0,
        description="AC3-3:設計温度差",
    )
    isStagingControl: Optional[Literal["有", "無"]] = Field(
        None,
        description="AC3-4:台数制御の有無",
    )
    SecondaryPump: Optional[List[SecondaryPumpItem]] = None


class AirHandlingUnitItem(BaseModel):
    Type: Optional[
        Literal[
            "空調機",
            "FCU",
            "送風機",
            "室内機",
            "全熱交ユニット",
            "放熱器",
            "天井放射冷暖房パネル",
        ]
    ] = Field(None, description="AC4-2:構成機種")
    Number: Optional[int] = Field(None, ge=0, description="AC4-3:台数")
    RatedCapacityCooling: Optional[float] = Field(
        None,
        ge=0,
        description="AC4-4:定格能力（冷却）",
    )
    RatedCapacityHeating: Optional[float] = Field(
        None,
        ge=0,
        description="AC4-5:定格能力（暖房）",
    )
    FanType: Optional[
        Literal[
            "給気",
            "還気",
            "外気",
            "排気",
            "循環",
            "ポンプ",
        ]
    ] = Field(None, description="AC4-6:送風機種類")
    FanAirVolume: Optional[float] = Field(None, ge=0, description="AC4-7:設計風量")
    FanPowerConsumption: Optional[float] = Field(
        None,
        ge=0,
        description="AC4-8:定格消費電力",
    )
    FanControlType: Optional[
        Literal[
            "無",
            "定風量制御",
            "回転数制御",
        ]
    ] = Field(None, description="AC4-9:風量制御方式")
    FanMinOpeningRate: Optional[float] = Field(
        None,
        ge=0,
        description="AC4-10:最小風量比",
    )
    AirHeatExchangeRatioCooling: Optional[float] = Field(
        None,
        ge=0,
        description="AC4-11:全熱交換効率 冷房時",
    )
    AirHeatExchangeRatioHeating: Optional[float] = Field(
        None,
        ge=0,
        description="AC4-12:全熱交換効率 暖房時",
    )
    AirHeatExchangerEffectiveAirVolumeRatio: Optional[float] = Field(
        None,
        ge=0,
        description="AC4-13:全熱交換器 有効換気量率",
    )
    AirHeatExchangerControl: Optional[Literal["有", "無"]] = Field(
        None,
        description="AC4-14:自動換気切替機能の有無",
    )
    AirHeatExchangerPowerConsumption: Optional[float] = Field(
        None,
        ge=0,
        description="AC4-15:ローター回転用電動機消費電力",
    )
    Info: Optional[str] = Field(None, description="AC4-23:備考")


class AirHandlingSystem(BaseModel):
    isEconomizer: Optional[Literal["無", "有"]] = Field(
        None,
        description="AC4-16:外気冷房制御の有無",
    )
    EconomizerMaxAirVolume: Optional[float] = Field(
        None,
        ge=0.0,
        description="AC4-17:外気冷房制御 最大外気取入量",
    )
    isOutdoorAirCut: Optional[Literal["無", "有"]] = Field(
        None,
        description="AC4-18:予熱時外気取入量制御の有無",
    )
    Pump_cooling: Optional[str] = Field(
        None,
        description="AC4-19:二次ポンプ群名称 冷房",
    )
    Pump_heating: Optional[str] = Field(
        None,
        description="AC4-20:二次ポンプ群名称 暖房",
    )
    HeatSorce_cooling: Optional[str] = Field(None, description="AC4-21:熱源群名称 冷房")
    HeatSorce_heating: Optional[str] = Field(None, description="AC4-22:熱源群名称 暖房")
    AirHandlingUnit: Optional[List[AirHandlingUnitItem]] = None


class VentilationRoom(BaseModel):
    VentilationType: Optional[Literal["一種換気", "二種換気", "三種換気"]] = Field(
        None,
        description="V1-3:換気方式",
    )
    VentilationUnitRef: Dict[str, VentilationUnitRef]


class VentilationUnitRef(BaseModel):
    UnitType: Optional[Literal["給気", "排気", "空調", "循環"]] = Field(
        None, description="V1-4:機器の種類"
    )
    Info: Optional[str] = Field(None, description="V1-6:備考")


class VentilationUnit(BaseModel):
    Number: int = Field(
        ...,
        ge=0,
        description="V2-2:台数",
    )
    FanAirVolume: Optional[float] = Field(
        ...,
        ge=0.0,
        description="V2-3:設計風量",
    )
    MoterRatedPower: Optional[float] = Field(
        ...,
        ge=0.0,
        description="V2-4:定格電動機出力",
    )
    PowerConsumption: Optional[float] = Field(
        ...,
        ge=0.0,
        description="V2-5:定格消費電力",
    )
    HighEfficiencyMotor: Literal["有", "無"] = Field(
        ...,
        description="V2-6:高効率電動機の有無",
    )
    Inverter: Literal["有", "無"] = Field(
        ...,
        description="V2-7:インバータの有無",
    )
    AirVolumeControl: Literal["無", "CO濃度制御", "温度制御"] = Field(
        ...,
        description="V2-8:送風量制御",
    )
    VentilationRoomType: Optional[
        Union[Literal["電気室", "機械室", "エレベータ機械室", "その他"], float]
    ] = Field(
        ...,
        description="V2-9:対象室の用途",
    )
    AC_CoolingCapacity: Optional[float] = Field(
        ...,
        ge=0.0,
        description="V2-10:必要冷却能力",
    )
    AC_RefEfficiency: Optional[float] = Field(
        ...,
        ge=0.0,
        description="V2-11:熱源効率(一次換算値)",
    )
    AC_PumpPower: Optional[float] = Field(
        ...,
        ge=0.0,
        description="V2-12:ポンプの定格消費電力",
    )
    Info: str = Field(..., description="V1-6:備考")


class LightingOccupantSensingCTRL(BaseModel):
    __root__: Union[Literal["無", "下限調光方式", "点滅方式", "減光方式"], float] = (
        Field(
            ...,
            description="L-11:在室検知制御",
        )
    )


class LightingIlluminanceSensingCTRL(BaseModel):
    __root__: Union[
        Literal[
            "無",
            "調光方式",
            "調光方式BL",
            "調光方式W15",
            "調光方式W15BL",
            "調光方式W20",
            "調光方式W20BL",
            "調光方式W25",
            "調光方式W25BL",
            "点滅方式",
        ],
        float,
    ] = Field(
        ...,
        description="L-12:明るさ検知制御",
    )


class LightingTimeScheduleCTRL(BaseModel):
    __root__: Union[Literal["無", "減光方式", "点滅方式"], float] = Field(
        ...,
        description="L-13:タイムスケジュール制御",
    )


class LightingInitialIlluminationCorrectionCTRL(BaseModel):
    __root__: Union[
        Literal[
            "無",
            "タイマ方式(LED)",
            "タイマ方式(蛍光灯)",
            "センサ方式(LED)",
            "センサ方式(蛍光灯)",
        ],
        float,
    ] = Field(
        ...,
        description="L-14:初期照度補正機能",
    )


class HotwaterSystemItem(BaseModel):
    UsageType: Optional[Literal["便所", "浴室", "厨房", "その他"]] = Field(
        None, description="HW1-3:給湯用途"
    )
    SystemName: Optional[str] = Field(None, description="HW1-4:給湯システム名称")
    HotWaterSavingSystem: Optional[Literal["自動給湯栓", "節湯B1", "無"]] = Field(
        None,
        description="HW1-5:節湯器具",
    )
    Info: Optional[str] = Field(None, description="HW1-6:備考")


class HotwaterRoom(BaseModel):
    HotwaterSystem: Optional[List[HotwaterSystemItem]] = None


class HeatSourceUnitItem(BaseModel):
    UsageType: Optional[
        Literal["給湯負荷用", "配管保温用", "貯湯槽保温用", "その他"]
    ] = Field(None, description="HW2-2:給湯用途")
    HeatSourceType: Optional[
        Literal[
            "ガス給湯機",
            "ガス給湯暖房機",
            "ボイラ",
            "石油給湯機(給湯単機能)",
            "石油給湯機(給湯機付ふろがま)",
            "家庭用ヒートポンプ給湯機",
            "業務用ヒートポンプ給湯機",
            "貯湯式電気温水器",
            "電気瞬間湯沸器",
            "真空式温水発生機",
            "無圧式温水発生機",
            "地域熱供給",
        ]
    ] = Field(None, description="HW2-3:熱源機種")
    Number: Optional[int] = Field(
        None,
        ge=0,
        description="HW2-4:台数",
    )
    RatedCapacity: Optional[float] = Field(
        None,
        ge=0.0,
        description="HW2-5:定格加熱能力",
    )
    RatedPowerConsumption: Optional[float] = Field(
        None,
        ge=0.0,
        description="HW2-6:定格消費電力",
    )
    RatedFuelConsumption: Optional[float] = Field(
        None,
        ge=0.0,
        description="HW2-7:定格燃料消費量(高位)",
    )
    Info: Optional[str] = Field(None, description="HW2-13:備考")


class HotwaterSupplySystems(BaseModel):
    HeatSourceUnit: Optional[List[HeatSourceUnitItem]] = None
    InsulationType: Optional[Literal["保温仕様1", "保温仕様2", "保温仕様3", "裸管"]] = (
        Field(
            None,
            description="HW2-8:配管保温仕様",
        )
    )
    PipeSize: Optional[float] = Field(
        None,
        ge=0.0,
        description="HW2-9:配管最大口径",
    )
    SolarSystemArea: Optional[float] = Field(
        None,
        ge=0.0,
        description="HW2-10:太陽熱利用 有効集熱面積",
    )
    SolarSystemDirection: Optional[float] = Field(
        None,
        ge=0.0,
        # le=360.0,
        description="HW2-11:太陽熱利用 集熱面の方位角",
    )
    SolarSystemAngle: Optional[float] = Field(
        None,
        ge=0.0,
        # le=360.0,
        description="HW2-12:太陽熱利用 集熱面の傾斜角",
    )


class ElevatorItem(BaseModel):
    ElevatorName: Optional[str] = Field(None, description="EV-3:昇降機系統の名称")
    Number: Optional[int] = Field(None, ge=0, description="EV-4:台数")
    LoadLimit: Optional[float] = Field(
        None,
        ge=0.0,
        description="EV-5:積載量",
    )
    Velocity: Optional[float] = Field(
        None,
        ge=0.0,
        description="EV-6:速度",
    )
    TransportCapacityFactor: Optional[float] = Field(
        None,
        ge=0.0,
        description="EV-7:輸送能力係数",
    )
    ControlType: Optional[
        Literal[
            "VVVF(電力回生なし)",
            "VVVF(電力回生あり)",
            "VVVF(電力回生なし、ギアレス)",
            "VVVF(電力回生あり、ギアレス)",
            "交流帰還制御",
        ]
    ] = Field(None, description="EV-6:速度")
    Info: Optional[str] = Field(None, description="EV-7:備考")


class Elevators(BaseModel):
    Elevator: Optional[List[ElevatorItem]] = None


class PhotovoltaicSystems(BaseModel):
    PowerConditionerEfficiency: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description="PV-2:パワーコンディショナの効率",
    )
    CellType: Optional[Literal["結晶系", "結晶系以外"]] = Field(
        None, description="PV-3:太陽電池の種類"
    )
    ArraySetupType: Optional[Literal["架台設置形", "屋根置き形", "その他"]] = Field(
        None,
        description="PV-4:アレイ設置方式",
    )
    ArrayCapacity: Optional[float] = Field(
        None,
        ge=0.0,
        description="PV-5:アレイのシステム容量",
    )
    Direction: Optional[float] = Field(
        None,
        ge=0.0,
        le=360.0,
        description="PV-6:パネルの方位角",
    )
    Angle: Optional[float] = Field(
        None,
        ge=0.0,
        le=180.0,
        description="PV-7:パネルの傾斜角",
    )
    Info: Optional[str] = Field(None, description="PV-8:備考")


class CogenerationSystems(BaseModel):
    RatedCapacity: Optional[float] = Field(
        None,
        ge=0.0,
        description="CG-2:定格発電出力",
    )
    Number: Optional[int] = Field(None, ge=0, description="CG-3:台数")
    PowerGenerationEfficiency_100: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description="CG-4:発電効率 負荷率1.00",
    )
    PowerGenerationEfficiency_75: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description="CG-5:発電効率 負荷率0.75",
    )
    PowerGenerationEfficiency_50: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description="CG-6:発電効率 負荷率0.50",
    )
    HeatGenerationEfficiency_100: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description="CG-7:排熱効率 負荷率1.00",
    )
    HeatGenerationEfficiency_75: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description="CG-8:排熱効率 負荷率0.75",
    )
    HeatGenerationEfficiency_50: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description="CG-9:排熱効率 負荷率0.50",
    )
    HeatRecoveryPriorityCooling: Optional[Literal["1番目", "2番目", "3番目"]] = Field(
        None,
        description="CG-10:排熱利用優先順位 空調冷熱源",
    )
    HeatRecoveryPriorityHeating: Optional[Literal["1番目", "2番目", "3番目"]] = Field(
        None,
        description="CG-11:排熱利用優先順位 空調温熱源",
    )
    HeatRecoveryPriorityHotWater: Optional[Literal["1番目", "2番目", "3番目"]] = Field(
        None,
        description="CG-12:排熱利用優先順位 給湯",
    )
    field_24hourOperation: Optional[Literal["有", "無"]] = Field(
        None,
        alias="24hourOperation",
        description="CG-13:24時間運転の有無",
    )
    CoolingSystem: Optional[str] = Field(
        None,
        description="CG-14:排熱利用系統 空調 冷熱",
    )
    HeatingSystem: Optional[str] = Field(
        None,
        description="CG-14:排熱利用系統 空調 温熱",
    )
    HowWaterSystem: Optional[str] = Field(None, description="CG-14:排熱利用系統 給湯")
    Info: Optional[str] = Field(None, description="PV-8:備考")


class Building(BaseModel):
    class Config:
        extra = ("forbid",)

    Name: Optional[str] = Field(..., description="BL-1:建築物の名称")
    BuildingAddress: Optional[BuildingAddress] = Field(
        None,
        description="BL-2,3,4:建築物所在地",
    )
    Region: int = Field(..., ge=1, le=8, description="BL-5:地域の区分")
    AnnualSolarRegion: Optional[
        Literal[
            "A1",
            "A2",
            "A3",
            "A4",
            "A5",
        ]
    ] = Field(None, description="BL-6:年間日射地域区分")
    BuildingFloorArea: Optional[float] = Field(
        None,
        ge=0,
        description="BL-7:延べ面積 [m2]",
    )
    Coefficient_DHC: Optional[CoefficientDHC] = Field(
        None,
        description="BL-8,9:「他人から供給された熱」の一次エネルギー換算係数",
    )


class ShadingConfigure(BaseModel):
    shadingEffect_C: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description="BE4-2:日除け効果係数（冷房）",
    )
    shadingEffect_H: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description="BE4-3:日除け効果係数（暖房）",
    )
    x1: Optional[ShadingLength] = None
    x2: Optional[ShadingLength] = None
    x3: Optional[ShadingLength] = None
    y1: Optional[ShadingLength] = None
    y2: Optional[ShadingLength] = None
    y3: Optional[ShadingLength] = None
    zxPlus: Optional[ShadingLength] = None
    zxMinus: Optional[ShadingLength] = None
    zyPlus: Optional[ShadingLength] = None
    zyMinus: Optional[ShadingLength] = None
    Info: Optional[str] = Field(None, description="BE4-14:備考")


class HeatsourceSystem(BaseModel):
    冷房: Optional[Heatsource] = None
    冷房_蓄熱_: Optional[Heatsource] = Field(None, alias="冷房(蓄熱)")
    暖房: Optional[Heatsource] = None
    暖房_蓄熱_: Optional[Heatsource] = Field(None, alias="暖房(蓄熱)")


class SecondaryPumpSystem(BaseModel):
    冷房: Optional[SecondaryPump] = None
    暖房: Optional[SecondaryPump] = None


class LightingUnit(BaseModel):
    class Config:
        extra = ("forbid",)

    RatedPower: Optional[float] = Field(
        None,
        ge=0.0,
        description="L-9:定格消費電力 [W/台]",
    )
    Number: Optional[int] = Field(
        1,
        ge=0,
        description="L-10:台数",
    )
    OccupantSensingCTRL: Optional[LightingOccupantSensingCTRL] = None
    IlluminanceSensingCTRL: Optional[LightingIlluminanceSensingCTRL] = None
    TimeScheduleCTRL: Optional[LightingTimeScheduleCTRL] = None
    InitialIlluminationCorrectionCTRL: Optional[
        LightingInitialIlluminationCorrectionCTRL
    ] = None


class LightingRoom(BaseModel):
    roomWidth: Optional[float] = Field(
        None,
        ge=0.0,
        description="L-4:室指数　室の間口 [m]",
    )
    roomDepth: Optional[float] = Field(
        None,
        ge=0.0,
        description="L-5:室指数　室の奥行 [m]",
    )
    unitHeight: Optional[float] = Field(
        None,
        ge=0.0,
        description="L-6:室指数\u3000器具高さ [m]",
    )
    roomIndex: Optional[float] = Field(
        None,
        ge=0.0,
        description="L-7:室指数 [-]",
    )
    lightingUnit: Dict[str, LightingUnit]


class WebプログラムVer3用JsonSchema(BaseModel):
    class Config:
        extra = ("forbid",)

    Building: Building = Field(..., description="様式BL")
    Rooms: Dict[str, Rooms] = Field(..., description="様式RM")
    EnvelopeSet: Optional[Dict[str, EnvelopeSet]] = Field(None, description="様式BE1")
    WallConfigure: Optional[Dict[str, WallConfigure]] = Field(
        None,
        description="様式BE2",
    )
    WindowConfigure: Optional[Dict[str, WindowConfigure]] = Field(
        None,
        description="様式BE3",
    )
    ShadingConfigure: Optional[Dict[str, ShadingConfigure]] = Field(
        None,
        description="様式BE4",
    )
    AirConditioningZone: Optional[Dict[str, AirConditioningZone]] = Field(
        None,
        description="様式AC1",
    )
    HeatsourceSystem: Optional[Dict[str, HeatsourceSystem]] = Field(
        None,
        description="様式AC2",
    )
    SecondaryPumpSystem: Optional[Dict[str, SecondaryPumpSystem]] = Field(
        None,
        description="様式AC3",
    )
    AirHandlingSystem: Optional[Dict[str, AirHandlingSystem]] = Field(
        None,
        description="様式AC4",
    )
    VentilationRoom: Optional[Dict[str, VentilationRoom]] = Field(
        None,
        description="様式V1",
    )
    VentilationUnit: Optional[Dict[str, VentilationUnit]] = Field(
        None,
        description="様式V2",
    )
    LightingSystems: Optional[Dict[str, LightingRoom]] = Field(
        None,
        description="様式L",
    )
    HotwaterRoom: Optional[Dict[str, HotwaterRoom]] = Field(None, description="様式HW1")
    HotwaterSupplySystems: Optional[Dict[str, HotwaterSupplySystems]] = Field(
        None,
        description="様式HW2",
    )
    Elevators: Optional[Dict[str, Elevators]] = Field(None, description="様式EV")
    PhotovoltaicSystems: Optional[Dict[str, PhotovoltaicSystems]] = Field(
        None,
        description="様式PV",
    )
    CogenerationSystems: Optional[Dict[str, CogenerationSystems]] = Field(
        None,
        description="様式CG",
    )
    SpecialInputData: Optional[Dict[str, Any]] = Field(None, description="様式SP")
